@startuml
!include https://raw.githubusercontent.com/plantuml-stdlib/C4-PlantUML/master/C4_Container.puml

!define DEVICONS https://raw.githubusercontent.com/tupadr3/plantuml-icon-font-sprites/master/devicons
!define FONTAWESOME https://raw.githubusercontent.com/tupadr3/plantuml-icon-font-sprites/master/font-awesome-5
!include DEVICONS/python.puml
!include FONTAWESOME/users.puml
!include FONTAWESOME/file.puml

LAYOUT_LANDSCAPE()

!$WHITE="#ffffff"
!$BLACK="#000000"

UpdateElementStyle("person", $bgColor=$WHITE, $fontColor=$BLACK, $borderColor=$BLACK, $shadowing="false")
UpdateElementStyle("container", $bgColor=$WHITE, $fontColor=$BLACK, $borderColor=$BLACK, $shadowing="false")

AddRelTag("blackrel", $textColor=$BLACK)
AddRelTag("blackrel", $lineColor=$BLACK)



Person(user, "User", "Person who needs visualizations", $sprite="users")

Container(app, "AlgTest pyProcess", "python", "Generates visualizations", $sprite="python")

ContainerDb(db, "Profile database", ".csv .json", "Device profiles for visualization", $sprite="file")

ContainerDb(vis, "Visualizations", ".html .png", , $sprite="file")

Rel(user, app, "Uses", "Bash/PowerShell", $tags="blackrel")
Rel_R(app, vis, "Writes", $tags="blackrel")
Rel_R(app, db, "Reads/Writes", $tags="blackrel")
@enduml
