@startuml
hide empty attributes
hide empty methods
hide circle

skinparam shadowing false
skinparam classFontStyle Bold
skinparam ActivityBackgroundColor Silver
skinparam ActivityBorderColor DimGray

left to right direction

skinparam class {
    BackgroundColor Cornsilk
    ArrowColor DimGray
    BorderThickness 1
    BorderColor DimGray
}

title "AlgTest pyProcess object diagram for TPM profiles"



class "ProfileTPM" as Object\ProfileTPM {
    **test_info**: dict[str, str]
}

class "ProfilePerformanceTPM" as Object\ProfilePerformanceTPM {
    **results**: dict[str, PerformanceResultTPM]
}

class "ProfileSupportTPM" as Object\ProfileSupportTPM {
    **results**: dict[str, SupportResultTPM]
}


class "MeasurementResultTPM" as Object\MeasurementResultTPM {
    **category**: str
}

class "PerformanceResultTPM" as Object\PerformanceResultTPM {
        **key_params**: str

        **algorithm**: str
        **key_length**: int
        **mode**: str
        **encrypt_decrypt**: str

        **data_length**: int
        **scheme**: str

        **operation_avg**: float
        **operation_min**: float
        **operation_max**: float

        **iterations**: int
        **successful**: int
        **failed**: int
        **error**: str

}

class "SupportResultTPM" as Object\SupportResultTPM {
    **name**: str
    **value**: str
}


Object\ProfileTPM <|---  Object\ProfileSupportTPM

Object\ProfileTPM <|---  Object\ProfilePerformanceTPM

Object\MeasurementResultTPM <|--- Object\PerformanceResultTPM

Object\MeasurementResultTPM <|--- Object\SupportResultTPM
@enduml
